# CSRF Authentication Failed

## Problem

어드민 페이지에 들어가려고 했더니 CSRF 검증에 실패하면서 요청이 중단되었다.

## Analysis

먼저 [CSRF](https://owasp.org/www-community/attacks/csrf#overview)이란 Cross-Site Request Forgery의 약자로써, 유저로 하여금 본인의 의지와는 무관하게 공격자의 의도에 따라 행동하게 하여 특정 웹페이지의 보안성을 떨어뜨리는 공격 기법을 의미한다.
가장 대표적인 예로 정체불명의 이메일이나 링크를 유저에게 보내는데 이때 보내지는 요청은 변조된 상태로 서버에 들어가게 된다.
Django에는 이미 CSRF 공격을 방어하기 위한 툴들이 갖춰져 있다.

CSRF 공격을 방어하는 작동 원리[^1]는 다양한데 그 중 한 가지로
CSRF 공격의 방어를 담당하는 주체인 [`CsrfViewMiddleware`](https://docs.djangoproject.com/en/5.0/ref/middleware/#django.middleware.csrf.CsrfViewMiddleware)가 [Origin Header](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Origin)을 먼저 검증하여 요청을 보낸 URL이
브라우저나 혹은 [`CSRF_TRUSTED_ORIGINS`](https://docs.djangoproject.com/en/dev/ref/settings/#std-setting-CSRF_TRUSTED_ORIGINS) 내부에 적힌 호스트 Origin으로부터 왔는지를 검증한다.

<br />

<center>
  <figure>
    <img
      src="https://www.imperva.com/learn/wp-content/uploads/sites/13/2019/01/csrf-cross-site-request-forgery.png"
      alt="csrf"
    />
    <figcaption>출처: Imperva</figcaption>
  </figure>
</center>

<br />

하지만 필자의 `settings.py`에선 Railway에 배포한 URL이 `CSRF_TRUSTED_ORIGINS` 배열 안에 등록이 되지 않았기 때문에 Django에선 해당 URL이 잘못된 URL이라 판단하고 접근 거부를 시켜버린 것이었다.

[^1]: 참조: [How it works](https://docs.djangoproject.com/en/dev/ref/csrf/#how-it-works)

## Solution

[KenWhitesell](https://forum.djangoproject.com/t/how-to-activate-csrf-token-for-railway-deployment/22334/2)의 답변과 [Railway의 Django 배포 문서 중 Step 2](https://railway.app/template/Rj_70k)의
답변을 참고해 `CSRF_TRUSTED_ORIGINS`에 Railway의 호스트 이름을 기입했다.

```py settings.py
# ...

# Railway CSRF Authentication
CSRF_TRUSTED_ORIGINS = ["https://*.up.railway.app"]

if not DEBUG:
    CSRF_TRUSTED_ORIGINS.append(env("RAILWAY_HOST_URL"))


# ...
```
